{
 "title": "Kubernetes: POD Overview",
 "description": "Per POD based overview ",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "POD Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Name",
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 1 },
   "options": { "content": "# ${pod}" },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "POD Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container=~\"$container\", image!=\"\", container!=\"POD\", image!=\"\"}[2m]))",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\", container!=\"POD\", container!=\"\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container,pod) (container_memory_working_set_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  }
 ]
}